config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :playlists
  resources :music_videos
  resources :songs
  resources :artists

  get '/about', to: 'application#about'
  get '/', to: 'application#home', as: 'home'
  get '/log_in', to: 'users#log_in'
  post '/users/log_user_in', to: 'users#log_user_in'
  post '/logout', to: 'application#logout'
  post 'delete_playlist', to: 'playlists#destroy'
  post '/delete_song', to: 'songs#destroy'
  post '/songs/add', to: 'songs#add'





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  has_many :playlists
  has_many :music_videos, through: :playlists 

  validates :username, uniqueness: true
  validates :username, presence: true
  validates :username, length: {minimum: 3}
  validates :password, length: {minimum: 3}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
    

  end 


  def show
    @user = User.find(params[:id])
    
  end

  def log_in
    @user = User.new 
    
    

    
  end 

  def log_user_in
    @user = User.find_by(username: user_params[:username])
    
    
    if @user && @user.password == user_params[:password]
      session[:user_id] = @user.id
      redirect_to @user
    else 
      @error = "Wrong username or password"
      redirect_to log_in_path
    end 


  end 

  def create
    @user = User.create(user_params)

    if @user.valid?
      session[:user_id] = @user.id
    redirect_to @user
    else 
      render :new
    end 
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/log_in.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="application.css">
    <title>Document</title>
</head>
<body>
    <div class="App">
        <div class="navBar">
            <div class ="navLinks">


            <%=link_to "Home", home_path%>
                <a><%=link_to "About", about_path%></a>
            </div>
        </div>

        <div class="main">
        <h1 class="midWords"> Log In </h1>
       <div class='form'>

            <%= form_for @user, :url => url_for(:controller => 'users', :action => 'log_user_in') do |f|%>
            <%= f.label :username%>
            <%= f.text_field :username%>
            <%= f.label :password%>
            <%= f.password_field :password%>
            <%= f.submit 'Log In'%>
            <% end %>

            <% if @error != nil %>
            <p><%= @error %></p>
            <% end %>

            <ul>
            <% if @user.errors.any? %>
            <%= pluralize(@user.errors.count, "error") %>
            <% @user.errors.full_messages.each do |msg| %>
            <li> <%= msg %></li>
                <% end %>
                <% end %>
            </ul>
        </div>

        </div>

        
    </div>

</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="application.css">
    <title>Document</title>
</head>
<body>
    <div class="App">
        <div class="navBar">
            <div class ="navLinks">

            <%=link_to "Home", home_path%>

                <a><%=link_to "About", about_path%></a>
            </div>
        </div>

        <div class="main">
        <h1 class="midWords"> Sign Up </h1>
<div class="form">
        <%= form_for @user do |f|%>
        <%= f.label :username%>
        <%= f.text_field :username%>
        <%= f.label :password%>
        <%= f.password_field :password%>
        <%= f.submit%>
        <% end %>

        <ul>
        <% if @user.errors.any? %>
        <%= pluralize(@user.errors.count, "error") %>
        <% @user.errors.full_messages.each do |msg| %>
           <li> <%= msg %></li>
            <% end %>
            <% end %>
        </ul>
        </div>
        </div>

        

    </div>

</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"> 
    <link rel="stylesheet" href="users.scss">
    <title>Document</title>
</head>
<body>
    <div class="App">
        <div class="navBar">
            <div class ="navLinks">


           

            <a>Logged in as <%= @user.username%></a>
            <a class="logout"><%= button_to "Log Out", logout_path %></a>




            </div>
        </div>

        <div class="main_user">
            <p class="welcome_user"> Welcome <%=@user.username%></p>

            <div class="playlists">
                <div class="playlists_inside">
                    <p>Playlists</p>
                    <%= link_to "Create Playlist", new_playlist_path %>
                    <ul>
                        <% @user.playlists.each do |playlist| %>
                        <li><%= link_to playlist.name, playlist_path(playlist) %> <%= button_to 'Delete', delete_playlist_path(playlist), params:{:id => playlist.id} %></li>
                        <% end %>


                    </ul>
                </div>
            </div>


        </div>





    </div>

</body>
</html>