config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :playlists
  resources :music_videos
  resources :songs
  resources :artists

  get '/about', to: 'application#about'
  get '/', to: 'application#home', as: 'home'
  get '/log_in', to: 'users#log_in'
  post '/users/log_user_in', to: 'users#log_user_in'
  post '/logout', to: 'application#logout'
  post 'delete_playlist', to: 'playlists#destroy'
  post '/delete_song', to: 'songs#destroy'
  post '/songs/add', to: 'songs#add'





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  has_many :music_videos
  has_many :playlists, through: :music_videos
end

app/controllers/songs_controller.rb
require_relative'../models/search.rb'
class SongsController < ApplicationController
  def index
  end

  def new

  end
  def add
    @search = Search.new
    if params[:search].empty?
      render '/songs/new'
    else
      @search.search = params[:search]
      @song = Song.new
      @artist = Artist.new
    end
  end

  def show
    @song = Song.find(params[:id])
    Emoji.create_translations("app/assets/stylesheets/emojihex.rtf")
    @lyrics = @song.lyrics
    
    
    yt = YtScraper.new(@song.artist.name,@song.name)

    @video_id = yt.get_id


  end


  def create
    @artist = Artist.find_or_create_by(name: params[:artist_name])

    lyrics  = Scraper.new(params[:artist_name],params[:name]).get_lyrics
    if lyrics == 0
      lyrics = "No Lyrics found"
      @song = Song.create(name: params[:name], artist_id: @artist.id, url_album: params[:url_album], lyrics: lyrics )
    else
      @song = Song.create(name: params[:name], artist_id: @artist.id, url_album: params[:url_album], lyrics: lyrics )
    end
    @playlist =  Playlist.find(session[:playlist_id])
    MusicVideo.create(song_id: @song.id, playlist_id: session[:playlist_id])
    redirect_to @playlist
  end

  def destroy
    @song = Song.find(params[:id])
    @musicvideo = MusicVideo.find_by(song_id: @song.id, playlist_id: session[:playlist_id])
    if @musicvideo

    @musicvideo.destroy
    end
    redirect_to playlist_path(session[:playlist_id])
  end





  # def song_params
  #   params.require(:song).permit(:name)
  # end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/add.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="application.css">
    <title>Document</title>
</head>
<body>
    <div class="App">
        <div class="navBar">
            <div class ="navLinks">



                <a>About</a>
            </div>
        </div>

        <div class="main">
        <h1 class="midWords"> Search results: </h1>
        <ul>

            <% @search.results.each do |i| %>
            <li class="results"><%= "#{i.keys[0]}: #{i.values[0]}" %>

              <%=button_to 'Add song', songs_path(@song), params:{:name => i.values[0], :artist_name => i.keys[0], :url_album => i.values[1]}%>
            </li><br>

            <%end%>
            <p class="results"><%= link_to 'Search Again', '/songs/new'%></p>

            </ul>
        </div>

        <!-- <div class="about">
            <p class="aboutTitle">About</p>

            <div class="aboutContainer">
                <div>
                    <p>things and stuff</p>
                </div>
                <div>
                    <p>stuff and things</p>
                </div>
            </div>
        </div> -->

    </div>

</body>
</html>

app/views/songs/create.html.erb
<h1>Songs#create</h1>
<p>Find me in app/views/songs/create.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="application.css">
    <title>Document</title>
</head>
<body>
    <div class="App">
        <div class="navBar">
            <div class ="navLinks">



                <a><%=link_to "About", about_path%></a>
            </div>
        </div>

        <div class="main">
          <p class="midWords">Search</p>
          <div class = "form">
            <%= form_tag songs_add_path, method:'post' do  %>

            <%= text_field_tag :search %>
            <%= submit_tag :search %>
            <%end%>
          </div>
        </div>

        <!-- <div class="about">
            <p class="aboutTitle">About</p>

            <div class="aboutContainer">
                <div>
                    <p>things and stuff</p>
                </div>
                <div>
                    <p>stuff and things</p>
                </div>
            </div>
        </div> -->

    </div>

</body>
</html>

app/views/songs/show.html.erb
<h1><%=@song.name%></h1>
<div background-color: #000>
<iframe src="https://www.youtube.com/embed/<%="#{@video_id}"%>?background=1&autoplay=1"autoplay; ></iframe>


  


    <div id ="over">
        <%  @lyrics.split("\n").each do |line| %> 
        <br>
        <%= Emoji.translate(line) %> <br>
        <%end%>
        
     
        


    </div>
</div>