config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :playlists
  resources :music_videos
  resources :songs
  resources :artists

  get '/about', to: 'application#about'
  get '/', to: 'application#home', as: 'home'
  get '/log_in', to: 'users#log_in'
  post '/users/log_user_in', to: 'users#log_user_in'
  post '/logout', to: 'application#logout'
  post 'delete_playlist', to: 'playlists#destroy'
  post '/delete_song', to: 'songs#destroy'
  post '/songs/add', to: 'songs#add'





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/playlist.rb
class Playlist < ApplicationRecord

  belongs_to :user
  has_many :music_videos, dependent: :destroy
  has_many :songs, through: :music_videos
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
  end

  def show
    @user = User.find(session[:user_id])
    @playlist = Playlist.find(params[:id])
    session[:playlist_id] = @playlist.id
  end

  def new 
    @user = User.find(session[:user_id])
    @playlist = Playlist.new
  end 

  def create
    @playlist = Playlist.create(playlist_params)
    @playlist.user_id = session[:user_id]
   @playlist.save
    redirect_to playlist_path(@playlist)
  end

  def update
  end

  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy
    @user = User.find(session[:user_id])
    redirect_to @user
  end

  private

  def playlist_params
    params.require(:playlist).permit(:name)
  end 
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/create.html.erb
<h1>Playlists#create</h1>
<p>Find me in app/views/playlists/create.html.erb</p>

app/views/playlists/delete.html.erb
<h1>Playlists#delete</h1>
<p>Find me in app/views/playlists/delete.html.erb</p>

app/views/playlists/index.html.erb
<h1>Playlists#index</h1>
<p>Find me in app/views/playlists/index.html.erb</p>

app/views/playlists/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="application.css">
    <title>Document</title>
</head>
<body>
    <div class="App">
        <div class="navBar">
            <div class ="navLinks">

        
            <a>Logged in as <%= @user.username%></a>
                <a> <%=link_to "About", about_path %> </a>
            </div>
        </div>

        <div class="main">
            <h1 class="midWords">Create Playlist</h1>
            <div class='form'>
                <%= form_for @playlist do |f|%>
                    <%= f.label :name%>
                    <%= f.text_field :name%>

                    <%= f.submit%>
                    <% end %>
            </div>
                  
        </div>

        <div class="about">
            <p class="aboutTitle">About</p>

            <div class="aboutContainer">
                <div>
                    <p>things and stuff</p>
                </div>
                <div>
                    <p>stuff and things</p>
                </div>
            </div>
        </div>

    </div>

</body>
</html>

app/views/playlists/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="playlists.css.css">
    <title>Document</title>
</head>
<body>
    <div class="App">
        <div class="navBar">
            <div class ="navLinks">
            <a>Logged in as <%= @user.username%></a>
            <%= link_to "Back to Profile", user_path(session[:user_id]) %>
            <%= link_to "About", about_path %>
              
                
            </div>
        </div>

        <div class="mainPlaylist">
            <h1 class="playlistMidWords"> <%= @playlist.name %></h2>
            <div class="songs">
                <h2> Songs:</h2>
                <ul>
                <% @playlist.songs.each do |song| %>
                <li> <img class="img" src=<%=song.url_album%>> <%= link_to song.name, song_path(song) %>, by <%= song.artist.name %>  <%= button_to 'Delete', delete_song_path(song), params:{:id => song.id} %></li>
                    <% end %>
                    </ul><br>
                <%= link_to "add song", new_song_path %> <br>
            </div>
        </div>

        
    </div>

</body>
</html>

app/views/playlists/update.html.erb
<h1>Playlists#update</h1>
<p>Find me in app/views/playlists/update.html.erb</p>