config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :playlists
  resources :music_videos
  resources :songs
  resources :artists

  get '/about', to: 'application#about'
  get '/', to: 'application#home', as: 'home'
  get '/log_in', to: 'users#log_in'
  post '/users/log_user_in', to: 'users#log_user_in'
  post '/logout', to: 'application#logout'
  post 'delete_playlist', to: 'playlists#destroy'
  post '/delete_song', to: 'songs#destroy'
  post '/songs/add', to: 'songs#add'





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def home

    end

    def new
    end

    def logout
        session[:user_id] = nil
        redirect_to :home
    end
    def about

    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="application.css">
    <title>Document</title>
</head>
<body>
    <div class="App">
        <div class="navBar">
            <div class ="navLinks">
            <%= link_to "Home", home_path %>

            </div>
        </div>

        <div class="main">

            <p class="midWords">About Kareoji</p>


            <p class="aboutText">
            We are the kings of emojis. None even come close to the precise art of mapping lyrical keywords to emoticon
           images. <br><br>Those who try (Apple, Samsung), quiver in fear of our algorithm, as it far surpasses their own.</p>
        </div>



    </div>

</body>
</html>

app/views/application/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="application.css">
    <title>Document</title>
</head>
<body>
    <div class="App">
        <div class="navBar">
            <div class ="navLinks">
            <%= link_to "Sign Up", new_user_path %>
            <%= link_to "Log In", log_in_path %>


                <a><%=link_to "About", about_path%></a>
            </div>
        </div>

        <div class="main">

            <p class="midWords">Welcome to Kareoji</p>
        </div>

       

    </div>

</body>
</html>